### ISSUE TITLE
Error in nodejs client when body includes unicode

### ISSUE THREAD

**Issue by kmamal** [kaltura/clients-generator#568] opened 2020-09-02 13:04 UTC
This line needs to go: https://github.com/kaltura/clients-generator/blob/292ed815b152a18999b53e1f4b8b4162f1a898c3/sources/node2/KalturaClientBase.js#L314

When the body includes unicode characters it incorrectly sets the content-length to the number of characters instead of the number of bytes.

**Comment by ronag** [comment] 2020-09-02 13:12
Should use `Buffer.byteLength`

**Comment by jessp01** [comment] 2020-09-02 13:17
Hello all,

See https://github.com/kaltura/clients-generator/pull/536/files

@zoharbabin FYI.

**Comment by kaltura-hooks** [comment] 2020-09-02 13:30
Hi @kmamal,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by andrewchart** [comment] 2021-01-16 11:22
Hi all. My team also ran into this issue using the NodeJS client library for Kaltura. 

I initially found [this issue report](https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS/issues/18) and debugged the issue within my project. Then I found this generator repo and the issues/PRs.

Removing the line which explicitly sets the `Content-Length` header (as suggested in [PR #518](https://github.com/kaltura/clients-generator/pull/518) and by @kmamal at the top of this issue) seems the simplest fix.

https://github.com/kaltura/clients-generator/pull/536 seems to have more comprehensive response handling but I don't know if there is any justification for continuing to explicitly set the `Content-Length` header? 

If there is a reason to set the header, @ronag's suggestion (use `Buffer`) is the simplest way to correctly calculate the length imo. `request` [already implements this](https://github.com/request/request/blob/3c0cddc7c8eb60b470e9519da85896ed7ee0081e/request.js#L424-L432) at a lower level.

Perhaps combining elements of both PRs would be a good solution? I don't see any value in me raising another PR.

Are there any plans to review and merge these PRs in the near future? I'd argue the Node client library is unusable with this bug.

Thanks
Andrew

**Comment by danielthedifficult** [comment] 2021-02-04 15:03
Hello, I'm also having this issue with very basic accent characters with the NodeJS client.

Any "é" in the name, description, or tags field causes this issue, as far as I can tell.

**Comment by danielthedifficult** [comment] 2021-02-23 23:16
@zoharbabin @jessp01 Is there something preventing this from being integrated? We're having this issue in production, none of our users can upload new entries with special characters using the API

**Comment by andrewchart** [comment] 2021-02-24 10:14
Hi @danielthedifficult - if it helps, I have temporarily patched this whilst waiting for the library fix. Please feel free to email me andrewc@andertons.co.uk if you want to know what I've done. It may be suitable for you.

**Comment by jessp01** [comment] 2021-02-24 14:20
Hi @andrewchart ,

Indeed, as you pointed out in your comment here https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS/issues/18#issuecomment-761029047, there are several different reports and suggestions around this issue.
I'd ideally like to consolidate them all into one PR and merge so we can release a new version. Since you say you've already applied fixes to your local version and tested, could you please comment and let me know whether there were other changes (not included in the current pending pull and previously merged ones ) that you had to make and what regression tests you've performed? If you'd like to submit a pull with additional changes, you're of course welcome to do so. Naturally, all contributors will be credited (but we will need you to sign the CLA).

Thanks in advance,

**Comment by danielthedifficult** [comment] 2021-02-24 14:25
Hi @andrewchart thanks for the offer, I appreciate it. I understand the fix - the problem is I have a serverless environment through a third party vendor, and I can't make modifications to npm packages used by the lambda functions (unless I make other, major, and frustrating modifications to my CI/CD pipeline).

I'm really hoping kaltura can get this implemented and then I can simply update to the latest package :-)


@jessp01 please see https://github.com/kaltura/clients-generator/pull/536 where @zoharbabin already has a PR... and he has probably signed the CLA ;)

**Comment by jessp01** [comment] 2021-02-24 14:30
Hi @danielthedifficult ,

@zoharbabin is a Kaltura employee so he doesn't need to sign a PR. However, if you review the other issues open around this problem, you'll see additional comments and suggestions. I'm therefore trying to understand whether there are other parts of the code that need fixing. 

> the problem is I have a serverless environment through a third party vendor, and I can't make modifications to npm packages used by my functions (unless I make other, major, and frustrating modifications to my CI/CD pipeline).

You can always fork this repo https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS, apply the changes and deploy from there. A pro tem solution, granted, but shouldn't be difficult.

**Comment by danielthedifficult** [comment] 2021-02-24 14:34
Thanks @jessp01, sorry if my humour didn't translate via the comment - I know @zoharbabin, I've had several conference calls with him to benefit from his wisdom on our project, we're a VPaaS customer.

(and I edited my comment above, I had read your comment too quickly before responding, my mistake!)

**Comment by jessp01** [comment] 2021-02-24 15:10
Hi @danielthedifficult,

No problem:) I'll wait for @andrewchart (or anyone else that was involved and has additional insights, for that matter) to reply. I'd like to get this sorted so we can release a new package.

**Comment by andrewchart** [comment] 2021-02-24 17:19
Hi @jessp01 

What I have implemented in my project is basically the same as [this PR](https://github.com/kaltura/clients-generator/pull/518) and the first comment in this issue. In other words, I made a single-line change to the `doHttpRequest` method which means that the Content-Length header is not set by the Kaltura library. 

In effect, this just means that the Content-Length header will be set by the underlying library (`request`) instead. My testing was simply to verify that the request sent to the API was the same except for the Content-Length header, and that `request` correctly calculates the Content-Length (which I believe it does) using `Buffer.byteLength()` rather than `String.length`.

Beyond this, I wouldn't say I have performed extensive regression testing. My assessment was that this change could only affect the inclusion of that header in the `options` object sent to `request`. I couldn't see how that could cause side effects elsewhere in the library. I can't say I know the library overall well enough to understand what might break, but it seems low risk to me.

Regarding [@zoharbabin's PR](https://github.com/kaltura/clients-generator/pull/536/commits): In my opinion this seems like it is writing code to work around an issue when the issue (the Content-Length) calculation could just be handed off to the `request` library. Again caveat being that he may know better than me why this would be a better solution :)

For the same reason, I think adding a `Buffer.byteLength` solution to the Kaltura library seems redundant to me.

In zoharbabin's PR, there seems to be an additional change to handle a both string and json responses. I think you'll know better than I will if this provides any value.

The second commit in zoharbabin's PR (the modification to the test) seems sensible to me. 

---

FWIW @danielthedifficult - the way I have applied this in my project didn't require any CI/CD changes; I'm still using the public version of the library. 

I created a new module which exported a function that is a line-for-line copy of the `doHttpRequest` method, except for the line where the Content-Length was set.

I then imported this into my code e.g

`import patchedDoHttpRequest from "kaltura.patch.js";`

Then, I modified the `RequestBuilder` object to use my method instead of the one from the library. (You need to `.bind()` the `RequestBuilder` because `doHttpRequest` uses `this`).

```
const requestBuilder = kaltura.services.media.add(entry);
requestBuilder.doHttpRequest = patchedDoHttpRequest.bind(requestBuilder);
```
---
I hope that clarifies my thoughts @jessp01. Is that enough to now combine the code into one PR? I feel like it might be better for you and your colleagues to decide what to combine and what not to include, but if you don't want to do the PR yourselves, I'm happy to do it if you can give me some direction on what you want in there, having heard my thoughts.

Thanks for working to get this merged, everyone.

Andy

**Comment by jessp01** [comment] 2021-02-25 11:23
Hi @andrewchart ,

Thank you for your inputs. Yes, it is very clear indeed and I agree with your risk assessment as well (although, you know how it goes, you never truly know the effect a change will have until after it's been in place for a while :)). I'll work on getting this in. I'd like everyone to bear in mind that releasing a new client version involves some procedural overhead that has nothing to do with this particular, uncomplicated fix so please do be patient. 

Cheers,

**Comment by jessp01** [comment] 2021-02-25 12:07
Hello all,

As noted previously, the `request` [NPM] library handles the `Content-Length` header quite well and there doesn't seem to be a need for additional manipulation within the `kaltura-client` code.

Dropping:
```js
options.headers['Content-Length'] = body.length;
```
as done by @nitzo here https://github.com/kaltura/clients-generator/pull/518#issue-381840827 seems to be enough. 
@zoharbabin - did you have a particular reason for introducing the changes here https://github.com/kaltura/clients-generator/pull/536/files instead?
If not, I suggest we just merge https://github.com/kaltura/clients-generator/pull/518 and revise the unit test such that the test entry name includes Unicode chars (which is what I asked for and you already did in your pull), to wit:

```js
        let entry = new kaltura.objects.MediaEntry({
                mediaType: kaltura.enums.MediaType.VIDEO,
                name: 'test עברית ﻉﺮﺒﻴﻫ हिन्दू
        });
```

Thanks,

**Comment by danielthedifficult** [comment] 2021-03-03 14:55
I would be soooo happy if this was merged before Friday :)

**Comment by zoharbabin** [comment] 2021-03-24 15:27
> @zoharbabin - did you have a particular reason for introducing the changes here https://github.com/kaltura/clients-generator/pull/536/files instead?
> If not, I suggest we just merge #518 and revise the unit test such that the test entry name includes Unicode chars (which is what I asked for and you already did in your pull)...

No special reason. let's go ahead and merge #518 . Thanks!

**Closed** 2022-01-29 18:39 UTC
